config/routes.rb
Rails.application.routes.draw do
  resources :results do
    member do
      get :setter
    end
  end
  resources :memberships, only: [:new, :edit, :create]
  resources :users, only: [:show, :new, :create]
  resources :leagues do
    resources :seasons do
      resources :teams
      resources :games
    end
  end
  root to: 'leagues#show'

  get 'sessions/new' => "sessions#new"
  post 'sessions/create' => "sessions#create"
  get 'sessions/logout' => "sessions#logout"

end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :league
  has_many :games
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_league, :set_season

  def show
    @seasons = Season.where(league_id: 1)

    @teams = Team.where(season_id: params[:id]).sort do |a, b|
      b.wins.count <=> a.wins.count
    end
    upcoming_games = Game.where(season_id: params[:id]).sort do |a, b|
      b.start_date <=> a.start_date
    end
    @upcoming_games = []
    upcoming_games.each do |game|
      if game.start_date > DateTime.now
        @upcoming_games << game
      end
    end
    @upcoming_games = @upcoming_games[0..4]

    recent_games = Game.where(season_id: params[:id]).sort do |a, b|
      b.start_date <=> a.start_date
    end
    @recent_games = []
    recent_games.each do |game|
      if game.start_date < DateTime.now
        @recent_games << game
      end
    end
    @recent_games = @recent_games[0..4]
    p @recent_games
  end

private

  # def find_games(games)
  #   scheduled_games = []
  #   games.each do |game|
  #     if game.start_date > DateTime.now
  #       scheduled_games << game
  #     end
  #   end
  #   scheduled_games
  # end
  def set_season
    @season = Season.find(params[:id])
  end

  def set_league
    @league = League.find(params[:league_id])
  end
end

app/views/seasons/show.html.erb
<h1> BUSCH LEAGUE </h1>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Seasons
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <% @seasons.each do |season| %>
    <a class="dropdown-item" href="/leagues/<%= params[:league_id] %>/seasons/<%= season.id %>"><%= season.name %></a>
    <% end %>
  </div>
</div>

<h3>Standings</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Team 
        <% if admin? %>
          <div class="edit" id="add-team">
            <%= link_to "+", new_league_season_team_path(season_id: params[:id]) %>
          </div>
        <% end %>

      </th>
      <th> Wins </th>
      <th> Losses </th>
    </tr>
  </thead>
  <tbody>
  <% @teams.each do |team| %>
    <tr>
      <% if team.users.include?(current_user) %>
      <td> <%= link_to "#{team.name}", [@league, @season, team], class: "highlight" %> </td>
      <% else %>
      <td> <%= link_to "#{team.name}", [@league, @season, team] %> </td>
      <% end %>
      <td> <%= team.wins.count %> </td>
      <td> <%= team.losses.count %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

<ul class= "upcoming">
  <h3> Upcoming Games: </h3>
  <% @upcoming_games.each do |game| %>
    <li> <%= link_to "#{game.start_date.strftime('%A, %B %d, %Y')}", [@league, @season, game] %> <%= Team.find(game.participants[0].team_id).name %> vs. <%= Team.find(game.participants[1].team_id).name %> </li>
  <% end %>
</ul>

<ul class= "recent">
  <h3> Recent Games: </h3>
  <% @recent_games.each do |game| %>
    <% if game.result == nil %>
    <li> <%= link_to "#{game.start_date.strftime('%A, %B %d, %Y')}", [@league, @season, game] %> <%= Team.find(game.participants[0].team_id).name %> TBD - <%= Team.find(game.participants[1].team_id).name %> TBD</li>
    <% else %>
      <li> <%= link_to "#{game.start_date.strftime('%A, %B %d, %Y')}", [@league, @season, game] %> <%= Team.find(game.participants[0].team_id).name %> <%= Result.find_by(game_id: game.id).winner_score %> - <%= Team.find(game.participants[1].team_id).name %> <%=Result.find_by(game_id: game.id).loser_score %></li>
    <% end %>
  <% end %>
</ul>