config/routes.rb
Rails.application.routes.draw do
  resources :results do
    member do
      get :setter
    end
  end
  resources :memberships, only: [:new, :edit, :create]
  resources :users, only: [:show, :new, :create]
  resources :leagues do
    resources :seasons do
      resources :teams
      resources :games
    end
  end
  root to: 'leagues#show'

  get 'sessions/new' => "sessions#new"
  post 'sessions/create' => "sessions#create"
  get 'sessions/logout' => "sessions#logout"

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :result
  belongs_to :season
  has_many :participants
  has_many :teams, through: :participants
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, :set_league, :set_season, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @game.update(game_params)
      redirect_to league_season_game_path
    else
      render :edit
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def set_season
    @season = Season.find(params[:season_id])
  end

  def set_league
    @league = League.find(params[:league_id])
  end

  def game_params
    params.require(:game).permit(:location, :start_date)
  end
end

app/views/games/_form.html.erb
<%= form_for([@league, @season, @game]) do |f| %>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_field :start_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Edit the Game</h1>

<%= render "form" %>

app/views/games/show.html.erb
<h1 class="header"><%= @season.name %></h1>
<div class="info">
  <div class="locate_date">
    <p class="location">Location: <span><%= @game.location %></span></p>
    <p class="date">Date: <span><%= @game.start_date.strftime('%A, %B %d, %Y') %></span></p>
    <%= link_to "Back", [@league, @season] %>
  </div>
  <div class="edit_links">
    <% if admin? || team_manager?(@game.participants[0].team) || team_manager?(@game.participants[1].team) %>
    <%= link_to "Edit Game", edit_league_season_game_path, class: "edit" %>
    <% unless @game.start_date > DateTime.now %>
      <% if @game.result == nil %>
        <%= link_to "Add Results", setter_result_path, class: "edit" %>
      <% else %>
        <%= link_to "Edit Results", edit_result_path, class: "edit" %>
      <% end %>
    <% end %>
  <% end %>
  </div>
</div>

<div class="details">
  <% unless @game.result == nil %>
  <div class="teams">
    <% if @game.result.winner %>
    <div class="team_box">
      <p><%= link_to "#{@game.result.winner.name}", [@league, @season, @game.result.winner], class: "team-name" %></p>
      <p class="team-score"><%= @game.result.winner_score %></p>
    </div>
    <div class="team_box">
      <p><%= link_to "#{@game.result.loser.name}", [@league, @season, @game.result.loser], class: "team-name" %></p>
      <p class="team-score"><%= @game.result.loser_score %></p>
    </div>
    <p><%= @game.result.description %></p>
    <% end %>
  <% else %>
    <p>Game Coming Soon!</p>
  <% end %>
  </div>
</div>